[plotly_artifacts]
git-tree-sha1 = "acfab6eba353d8a1ee1fc6848f00f7ff1f0faded"

    [[plotly_artifacts.download]]
    sha256 = "031cd61e5a48c7308acb13010980b42f8a46b16c7b127e88cd0a4552c77bfb8e"
    url = "https://gist.github.com/joshday/975a62b1f3f9ec6f0908092b662f0283/raw/acfab6eba353d8a1ee1fc6848f00f7ff1f0faded.tar.gz"
