[plotly_artifacts]
git-tree-sha1 = "acfab6eba353d8a1ee1fc6848f00f7ff1f0faded"

    [[plotly_artifacts.download]]
    sha256 = "bda23e7939373f83fd83e0b2c09dceb7db5aa81b676492ed61f2b28f2fee11f5"
    url = "https://gist.github.com/joshday/2c2dd4885c789ecc91e32f893ef37869/raw/acfab6eba353d8a1ee1fc6848f00f7ff1f0faded.tar.gz"
